import type { Metadata } from "next";
import "./globals.css";
import { DevPinProvider } from "../context/dev-pin-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <DevPinProvider>{children}</DevPinProvider>
      </body>
    </html>
  );
}
